# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0471fb4646d0d4281ce490c807e6b91"
name = "DevsApiG"
application_url = "https://cartridges-despite-telecommunications-advise.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tool/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [ "https://cartridges-despite-telecommunications-advise.trycloudflare.com/auth/callback", "https://cartridges-despite-telecommunications-advise.trycloudflare.com/auth/shopify/callback", "https://cartridges-despite-telecommunications-advise.trycloudflare.com/api/auth/callback" ]

[app_proxy]
url = "https://cartridges-despite-telecommunications-advise.trycloudflare.com/api"
subpath = "instagram-feed-track"
prefix = "apps"
